import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'fr' | 'en';

export const translations = {
  fr: {
    streak: 'Série',
    rank_elo: 'RANG ELO',
    play: 'JOUER',
    mode_classic: 'Mode Classique',
    mode_rapid: 'Duel Rapide',
    mode_daily: 'Défi Quotidien',
    mode_classic_desc: 'Partie jusqu’à épuisement des cartes.',
    mode_rapid_desc: '3 minutes pour dominer l’arène.',
    mode_daily_desc: 'Scénario spécial renouvelé chaque jour.',
    friends_online: 'Amis en ligne',
    see_all: 'Voir tout',
    random_encounters: 'Rencontres aléatoires',
    refresh: 'Actualiser',
    toggle_language: 'Changer la langue',
    view_stats: 'Voir les statistiques',
    global_leaderboard: 'Classement mondial',
    country_leaderboard: 'Classement national',
    no_country_leaderboard: 'Aucun classement disponible pour ce pays.',
    no_history: 'Aucun match joué pour le moment.',
    start_duel: 'Lancer le duel',
    view_daily_details: 'Voir le défi',
    daily_challenge_title: 'Défi quotidien',
    daily_challenge_story: 'Affrontez un adversaire légendaire pour gagner un badge exclusif.',
    challenge_reward: 'Récompense',
    rapid_time_left: 'Temps restant',
    back_to_modes: 'Retour aux modes',
    challenge: 'Défier',
    online: 'En ligne',
    in_game: 'En Jeu',
    offline: 'Hors ligne',
    tap_start: 'Touche pour commencer',
    tap_card: 'Touche ta carte',
    ready_fight: 'Prêt à combattre ?',
    duel_imminent: 'Duel imminent...',
    battle: 'PUGNA REGALIS !',
    round_won: 'Manche Gagnée !',
    round_lost: 'Manche Perdue...',
    touch_to_see: 'TOUCHER POUR VOIR',
    look_card: 'Regarde ta carte...',
    your_turn: 'À ton tour...',
    fight: 'COMBATTRE',
    waiting: 'En attente...',
    victory: 'VICTOIRE',
    defeat: 'DÉFAITE',
    won_all: 'Vous avez remporté toutes les cartes.',
    lost_all: 'Vous avez perdu toutes vos cartes.',
    return_menu: 'Retour au Menu',
    ready: 'PRÊT',
    pot: 'EN JEU',
    me: 'TOI',
    opponent: 'Adversaire',
    my_profile: 'Mon Profil',
    profile_settings: 'Configurer le profil',
    profile_subtitle: 'Personnalise ton identité dans l’arène.',
    player_name: 'Nom / Pseudo',
    country_code: 'Code pays (ex: FR)',
    avatar_url: 'URL de l’avatar',
    save_changes: 'Enregistrer',
    profile_saved: 'Profil mis à jour !',
    current_rank: 'Rang Actuel',
    top_percent: 'TOP 5%',
    win_rate: 'Victoires',
    success_rate: 'Taux de succès',
    games: 'Parties',
    games_played: 'Jouées au total',
    record: 'Record',
    cards_won: 'Cartes',
    cards_captured: 'Cartes capturées',
    history: 'Derniers Matchs',
    jack: 'V',
    queen: 'D',
    king: 'R',
    ace: 'A',
  },
  en: {
    streak: 'Streak',
    rank_elo: 'ELO RANK',
    play: 'PLAY',
    mode_classic: 'Classic Mode',
    mode_rapid: 'Rapid Duel',
    mode_daily: 'Daily Challenge',
    mode_classic_desc: 'Play until every card is captured.',
    mode_rapid_desc: '3 minutes to claim victory.',
    mode_daily_desc: 'A scripted scenario refreshed every day.',
    friends_online: 'Online Friends',
    see_all: 'See All',
    random_encounters: 'Random Encounters',
    refresh: 'Refresh',
    toggle_language: 'Toggle language',
    view_stats: 'View stats',
    global_leaderboard: 'Global leaderboard',
    country_leaderboard: 'Country leaderboard',
    no_country_leaderboard: 'No leaderboard available for this country.',
    no_history: 'No matches played yet.',
    start_duel: 'Start duel',
    view_daily_details: 'View challenge',
    daily_challenge_title: 'Daily Challenge',
    daily_challenge_story: 'Face a legendary opponent to earn an exclusive badge.',
    challenge_reward: 'Reward',
    rapid_time_left: 'Time left',
    back_to_modes: 'Back to modes',
    challenge: 'Challenge',
    online: 'Online',
    in_game: 'In Game',
    offline: 'Offline',
    tap_start: 'Tap to start',
    tap_card: 'Tap your card',
    ready_fight: 'Ready to fight?',
    duel_imminent: 'Duel imminent...',
    battle: 'PUGNA REGALIS!',
    round_won: 'Round Won!',
    round_lost: 'Round Lost...',
    touch_to_see: 'TAP TO REVEAL',
    look_card: 'Check your card...',
    your_turn: 'Your turn...',
    fight: 'FIGHT',
    waiting: 'Waiting...',
    victory: 'VICTORY',
    defeat: 'DEFEAT',
    won_all: 'You have won all the cards.',
    lost_all: 'You have lost all your cards.',
    return_menu: 'Back to Menu',
    ready: 'READY',
    pot: 'AT STAKE',
    me: 'YOU',
    opponent: 'Opponent',
    my_profile: 'My Profile',
    profile_settings: 'Customize profile',
    profile_subtitle: 'Set how other players see you.',
    player_name: 'Name / Nickname',
    country_code: 'Country code (ex: US)',
    avatar_url: 'Avatar URL',
    save_changes: 'Save',
    profile_saved: 'Profile updated!',
    current_rank: 'Current Rank',
    top_percent: 'TOP 5%',
    win_rate: 'Win Rate',
    success_rate: 'Success rate',
    games: 'Games',
    games_played: 'Total played',
    record: 'Record',
    cards_won: 'Cards',
    cards_captured: 'Cards captured',
    history: 'Match History',
    jack: 'J',
    queen: 'Q',
    king: 'K',
    ace: 'A',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations.fr;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
